# Generated by Django 5.0.2 on 2024-03-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='limited_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
